### `Data manipulation`
1. Acquire them, 2. Process them <br>

Tensor class supports automatic differentiation and it leverages GPU's to accelerate numerical computation
NumPy only runs on CPU's.

In [1]:
import torch

Tensor rep (possibly multidimensional) array of numerical values <br>
one axis is needed for the data. a tensor is called `vector` <br>
two axis, tensor is a `matrix` 

In [4]:
x= torch.arange(12, dtype=torch.float32)  
x
 #Unless otherwiese specified, new tensor are stored in main memory and designaed for CPU-based computation
 #Each of the values is called an `element` of the tensor

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [5]:
# Total number of elements in a tensor
x.numel()

12

In [6]:
x.shape

torch.Size([12])

In [7]:
#Changing the shape of tensor without altering its size or value
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [11]:
#tensors initialized to contain all 0's or 1's
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
#create a tensor with elements drawn from a standard gaussian distribution with mean 0 and Standard distribution 1

torch.randn(3,4)

tensor([[-0.9635,  0.3293,  1.2252,  1.1518],
        [-1.3373, -0.3556,  1.2278,  0.2825],
        [-0.2087, -0.0245,  0.8981,  0.3579]])

In [14]:
torch.tensor([ [3,2,5], [4,6,2], [8,5,6] ])

tensor([[3, 2, 5],
        [4, 6, 2],
        [8, 5, 6]])

### `Indexing and slicing`

In [15]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [16]:
X[-1], X[1:3]   #selects rows

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [17]:
X[1,2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [18]:
# assigning multiple elements the same value

X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### `Operations`

In [19]:
#manipulating with various mathematical operations
#Elementwise operations - apply a standard scaler op to each element of tensor
# unary scaler ops by signature f: R->R (funtion maps from any real number onto some other real number)


torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [20]:
# f:R,R -> R (binary scalar operations)
# +, -, *, "/", **

x= torch.tensor([1,2,3])
y= torch.tensor([4,5,6])
x+y, x-y, x*y, x/y, x**y

(tensor([5, 7, 9]),
 tensor([-3, -3, -3]),
 tensor([ 4, 10, 18]),
 tensor([0.2500, 0.4000, 0.5000]),
 tensor([  1,  32, 729]))

In [21]:
#Concatenate multiple tensors

X= torch.arange(12, dtype=torch.float32).reshape(3,4)
Y= torch.tensor([[1,2,3,4],[1,2,6,7],[9,3,6,1]])

torch.cat((X,Y), dim=0), torch.cat((X,Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  2.,  3.,  4.],
         [ 1.,  2.,  6.,  7.],
         [ 9.,  3.,  6.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  6.,  7.],
         [ 8.,  9., 10., 11.,  9.,  3.,  6.,  1.]]))

In [22]:
#logical statments
X==Y

tensor([[False, False, False, False],
        [False, False,  True,  True],
        [False, False, False, False]])

In [23]:
X.sum()

tensor(66.)

### Broadcasting

Broadcsting rule relaxes when two arrays shapes meet certain constraints, <br>


In [24]:
a= torch.arange(3).reshape(3,1)
b= torch.arange(2).reshape(1,2)

a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

matrix `b` being streched during the arthematic operation into an array with same shape as `a` <br>
The streching analogy is only conceptual <br>
torch is smart enough to use the original matrix without actually making copies so that broadcasting op are as memory and computationally efficient


In [25]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### Saving Memory

Running operations can cause new memory to be allocated to host results. For example, if we write Y = X + Y, we dereference the tensor that Y used to point to and instead point Y at the newly allocated memory

In [30]:
before = id(Y)
Y=X+Y
id(Y) == before

False

In ML, we often have 100's of MB of params and update all of them multiple times/sec. Whenever possible, we wan to perform these updates `in-place`

In [27]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))

Z[:] = X+Y
print('id(Z):', id(Z))

id(Z): 1817209682016
id(Z): 1817209682016


In [29]:
before = id(X)
X+=Y
id(X) ==  before

True

### Conversation to Other Python Objects

In [31]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [32]:
a= torch.tensor([2.3])

a, a.item(), float(a), int(a)

(tensor([2.3000]), 2.299999952316284, 2.299999952316284, 2)