-> Calculating derivatives is the crucial step in all optimization algorithm <br>
-> Working them by hand can be tedious and error prone. <br>
-> All modern deep learning frameworks take this work off our plates by offerering Automatic differentiations(`autograd`). <br>
-> Data pass through successive function, the framework builds a computational graph that tracks how each value depends on others. <br>
-> 

In [1]:
import torch

### `Simple Function`

-> Interested in differentiating the function `y = 2*x.T*x` with respect to the column vector x. To start, we assign x an initial value

In [2]:
x= torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
x.requires_grad_(True)
x.grad

In [4]:
#Now we Calculate our function of x and assign the result to y

y = 2 * torch.dot(x ,x)
y

tensor(28., grad_fn=<MulBackward0>)

-> We can now take the gradient of y wrt x by calling the backward method. 

In [5]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

-> We already know that the gradient of the function y=2 * x ** 2  wrt x should be 4x. We can now verify that the automatic gradient computation and <br> 
  the expected results are identical

In [6]:
x.grad == 4 * x

tensor([True, True, True, True])

In [8]:
x.grad.zero_()
y = x.sum()
y

tensor(6., grad_fn=<SumBackward0>)

In [9]:
y.backward()
x. grad

tensor([1., 1., 1., 1.])